### ISSUE TITLE
_wmi is the part of sys.stdlib_module_names (python 3.12.7/ 3.13.0)

### ISSUE THREAD

**Issue by stanislavlevin** [omnilib/stdlibs#117]
With `python 3.12.7 / 3.13.0 ` the `test_sys_stdlib_modules_agrees` test fails:
```
FAIL: test_sys_stdlib_modules_agrees (stdlibs.tests.StdlibsTest.test_sys_stdlib_modules_agrees)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/python3-module-stdlibs-2024.5.15/stdlibs/tests/__init__.py", line 47, in test_sys_stdlib_modules_agrees
    self.assertEqual(frozenset(), sys.stdlib_module_names - names)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Items in the second set but not the first:
'_wmi'

----------------------------------------------------------------------
Ran 7 tests in 0.085s

FAILED (failures=1)
```

See for details:
https://docs.python.org/3.12/whatsnew/changelog.html#python-3-12-7-final
https://github.com/python/cpython/issues/123892

**Comment by amyreese** [comment]
Looks like this module's filename (`PC/_wmimodule.cpp`) does not match it's importable name. Maybe we need to be more discerning and actually parse C files for `PyMODINIT_FUNC` macros rather than just assuming a 1:1 mapping. 

cc @thatch in case you have opinions.

**Comment by amyreese** [comment]
Scratch that, I hadn't looked too much at the fetch script yet. I just realized that we're only looking at `*.c` files, which is why me missed `_wmimodule.cpp`.

**Comment by stanislavlevin** [comment]
Thanks!
